const ROMAJI_TABLE = [
  [
    ["あ", "a"],
    ["い", "i"],
    ["う", "u"],
    ["え", "e"],
    ["お", "o"],
  ],
  [
    ["か", "ka, ca"],
    ["き", "ki"],
    ["く", "ku, cu"],
    ["け", "ke"],
    ["こ", "ko"],
  ],
  [
    ["が", "ga"],
    ["ぎ", "gi"],
    ["ぐ", "gu"],
    ["げ", "ge"],
    ["ご", "go"],
  ],
  [
    ["さ", "sa"],
    ["し", "si, ci"],
    ["す", "su"],
    ["せ", "se, ce"],
    ["そ", "so"],
  ],
  [
    ["ざ", "za"],
    ["じ", "zi, ji"],
    ["ず", "zu"],
    ["ぜ", "ze"],
    ["ぞ", "zo"],
  ],
  [
    ["た", "ta"],
    ["ち", "chi"],
    ["つ", "tsu, tu"],
    ["て", "te"],
    ["と", "to"],
  ],
  [
    ["だ", "da"],
    ["ぢ", "di"],
    ["づ", "du"],
    ["で", "de"],
    ["ど", "do"],
  ],
  [
    ["な", "na"],
    ["に", "ni"],
    ["ぬ", "nu"],
    ["ね", "ne"],
    ["の", "no"],
  ],
  [
    ["は", "ha"],
    ["ひ", "hi"],
    ["ふ", "hu"],
    ["へ", "he"],
    ["ほ", "ho"],
  ],
  [
    ["ば", "ba"],
    ["び", "bi"],
    ["ぶ", "bu"],
    ["べ", "be"],
    ["ぼ", "bo"],
  ],
  [
    ["ぱ", "pa"],
    ["ぴ", "pi"],
    ["ぷ", "pu"],
    ["ぺ", "pe"],
    ["ぽ", "po"],
  ],
  [
    ["ま", "ma"],
    ["み", "mi"],
    ["む", "mu"],
    ["め", "me"],
    ["も", "mo"],
  ],
  [
    ["や", "ya"],
    ["", ""],
    ["ゆ", "yu"],
    ["", ""],
    ["よ", "yo"],
  ],
  [
    ["や (小)", "xya, lya"],
    ["", ""],
    ["ゆ (小)", "xyu, lyu"],
    ["", ""],
    ["よ (小)", "xyo, lyo"],
  ],
  [
    ["ら", "ra"],
    ["り", "ri"],
    ["る", "ru"],
    ["れ", "re"],
    ["ろ", "ro"],
  ],
  [
    ["わ", "wa"],
    ["", ""],
    ["を", "wo"],
    ["", ""],
    ["ん", "nn, xn"],
  ],
];

const KEYBOARD_ROWS = [
  [
    { id: "1", label: "1" },
    { id: "2", label: "2" },
    { id: "3", label: "3" },
    { id: "4", label: "4" },
    { id: "5", label: "5" },
    { id: "6", label: "6" },
    { id: "7", label: "7" },
    { id: "8", label: "8" },
    { id: "9", label: "9" },
    { id: "0", label: "0" },
    { id: "-", label: "-" },
    { id: "blank-1", label: "", blank: true },
    { id: "blank-2", label: "", blank: true },
  ],
  [
    { id: "blank-3", label: "", blank: true },
    { id: "q", label: "Q" },
    { id: "w", label: "W" },
    { id: "e", label: "E" },
    { id: "r", label: "R" },
    { id: "t", label: "T" },
    { id: "y", label: "Y" },
    { id: "u", label: "U" },
    { id: "i", label: "I" },
    { id: "o", label: "O" },
    { id: "p", label: "P" },
    { id: "@", label: "@" },
  ],
  [
    { id: "blank-4", label: "", blank: true },
    { id: "a", label: "A" },
    { id: "s", label: "S" },
    { id: "d", label: "D" },
    { id: "f", label: "F" },
    { id: "g", label: "G" },
    { id: "h", label: "H" },
    { id: "j", label: "J" },
    { id: "k", label: "K" },
    { id: "l", label: "L" },
    { id: ";", label: ";" },
    { id: ":", label: ":" },
  ],
  [
    { id: "shift-l", label: "Shift", wide: "shift" },
    { id: "z", label: "Z" },
    { id: "x", label: "X" },
    { id: "c", label: "C" },
    { id: "v", label: "V" },
    { id: "b", label: "B" },
    { id: "n", label: "N" },
    { id: "m", label: "M" },
    { id: ",", label: "," },
    { id: ".", label: "." },
    { id: "/", label: "/" },
    { id: "shift-r", label: "Shift", wide: "shift" },
  ],
  [
    { id: "blank-5", label: "", blank: true },
    { id: "blank-6", label: "", blank: true },
    { id: "blank-7", label: "", blank: true },
    { id: " ", label: "공간", wide: "space" },
    { id: "blank-8", label: "", blank: true },
    { id: "blank-9", label: "", blank: true },
    { id: "blank-10", label: "", blank: true },
  ],
];
